name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.branch }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        branch:
          - openwrt-25.12
          - SNAPSHOT

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: mihomo-alpha mihomo-meta nikki luci-app-nikki
          INDEX: 1
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}          
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/nikki
