name: Test

on:
  workflow_dispatch:

jobs:
  current_mihomo:
    runs-on: ubuntu-26.04
    outputs:
      mihomo_alpha_pkg_source_version: ${{ steps.current.outputs.mihomo_alpha_pkg_source_version }}
      mihomo_meta_pkg_source_version: ${{ steps.current.outputs.mihomo_meta_pkg_source_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: apoiston/nikki
          ref: main
          path: OpenWrt-nikki

      - name: Current mihomo
        id: current
        run: |
          echo "mihomo_alpha_pkg_source_version=$(grep -E "^PKG_SOURCE_VERSION:=" OpenWrt-nikki/mihomo-alpha/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "mihomo_meta_pkg_source_version=$(grep -E "^PKG_SOURCE_VERSION:=" OpenWrt-nikki/mihomo-meta/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT

  latest_mihomo_alpha:
    runs-on: ubuntu-26.04
    outputs:
      mihomo_alpha_pkg_version_latest: ${{ steps.latest.outputs.mihomo_alpha_pkg_version_latest }}
      mihomo_alpha_pkg_source_version_latest: ${{ steps.latest.outputs.mihomo_alpha_pkg_source_version_latest }}
      mihomo_alpha_pkg_mirror_hash_latest: ${{ steps.latest.outputs.mihomo_alpha_pkg_mirror_hash_latest }}
      mihomo_alpha_pkg_build_version_latest: ${{ steps.latest.outputs.mihomo_alpha_pkg_build_version_latest }}
      mihomo_alpha_version: ${{ steps.latest.outputs.mihomo_alpha_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: MetaCubeX/mihomo
          ref: Alpha
          path: mihomo-alpha

      - name: Latest mihomo alpha
        id: latest
        run: |
          umask 0022
          git -C mihomo-alpha config core.abbrev 8
          mihomo_alpha_commit_date=$(git -C mihomo-alpha log -n 1 --format=%cd --date=format:%Y.%m.%d)
          mihomo_alpha_commit_timestamp=$(git -C mihomo-alpha log -n 1 --format=%cd --date=format:%s)
          mihomo_alpha_commit_hash=$(git -C mihomo-alpha rev-parse HEAD)          
          mihomo_alpha_commit_hash_short=$(git -C mihomo-alpha rev-parse --short=7 HEAD)
          mihomo_alpha_pkg_version_latest="${mihomo_alpha_commit_date}~${mihomo_alpha_commit_hash_short}"
          mihomo_alpha_pkg_name="mihomo-alpha"
          mihomo_alpha_source_dir="${mihomo_alpha_pkg_name}-${mihomo_alpha_pkg_version_latest}"
          mihomo_alpha_source_archive="${mihomo_alpha_source_dir}.tar.gz"
          mkdir -p "${mihomo_alpha_source_dir}"
          git -C mihomo-alpha archive --format=tar HEAD | tar -x -f - -C "${mihomo_alpha_source_dir}"
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name --mtime="@${mihomo_alpha_commit_timestamp}" -c "${mihomo_alpha_source_dir}" | gzip -n -c > "${mihomo_alpha_source_archive}"

          echo "mihomo_alpha_pkg_version_latest=${mihomo_alpha_pkg_version_latest}" >> $GITHUB_OUTPUT
          echo "mihomo_alpha_pkg_source_version_latest=${mihomo_alpha_commit_hash}" >> $GITHUB_OUTPUT
          echo "mihomo_alpha_pkg_mirror_hash_latest=$(sha256sum ${mihomo_alpha_source_archive} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "mihomo_alpha_pkg_build_version_latest="alpha-${mihomo_alpha_commit_hash_short}"" >> $GITHUB_OUTPUT
          echo "mihomo_alpha_version="${mihomo_alpha_commit_hash_short}"" >> $GITHUB_OUTPUT

  update_mihomo_alpha:
    needs:
      - current_mihomo
      - latest_mihomo_alpha
    if: ${{ needs.current_mihomo.outputs.mihomo_alpha_pkg_source_version != needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_source_version_latest }}
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: apoiston/nikki
          ref: main
          path: OpenWrt-nikki

      - name: Update mihomo alpha
        run: |
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_version_latest }}/" OpenWrt-nikki/mihomo-alpha/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_source_version_latest }}/" OpenWrt-nikki/mihomo-alpha/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_mirror_hash_latest }}/" OpenWrt-nikki/mihomo-alpha/Makefile
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_build_version_latest }}/" OpenWrt-nikki/mihomo-alpha/Makefile

      - name: PR
        id: pr
        uses: peter-evans/create-pull-request@v8
        with:
          path: OpenWrt-nikki
          branch: dependabot/mihomo-alpha
          commit-message: "chore: update mihomo-alpha to ${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_version }}"
          title: "chore: update mihomo-alpha to ${{ needs.latest_mihomo_alpha.outputs.mihomo_alpha_version }}"
          body: |
            [Changelog](https://github.com/metacubex/mihomo/compare/${{ needs.current_mihomo.outputs.mihomo_alpha_pkg_source_version }}...${{  needs.latest_mihomo_alpha.outputs.mihomo_alpha_pkg_source_version_latest }})

  latest_mihomo_meta:
    runs-on: ubuntu-26.04
    outputs:
      mihomo_meta_pkg_version_latest: ${{ steps.latest.outputs.mihomo_meta_pkg_version_latest }}
      mihomo_meta_pkg_source_version_latest: ${{ steps.latest.outputs.mihomo_meta_pkg_source_version_latest }}
      mihomo_meta_pkg_mirror_hash_latest: ${{ steps.latest.outputs.mihomo_meta_pkg_mirror_hash_latest }}
      mihomo_meta_pkg_build_version_latest: ${{ steps.latest.outputs.mihomo_meta_pkg_build_version_latest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: MetaCubeX/mihomo
          ref: Meta
          path: mihomo-meta
          fetch-tags: true

      - name: Latest mihomo meta
        id: latest
        run: |
          umask 0022
          git -C mihomo-meta config core.abbrev 8
          mihomo_meta_latest_tag=$(git -C mihomo-meta tag --sort=-v:refname | head -n 1)
          mihomo_meta_pkg_version_latest=${mihomo_meta_latest_tag#v}
          mihomo_meta_pkg_source_version_latest=${mihomo_meta_latest_tag}
          git -C mihomo-meta checkout "${mihomo_meta_latest_tag}"
          mihomo_meta_commit_timestamp=$(git -C mihomo-meta log -n 1 --format=%cd --date=format:%s)
          mihomo_meta_pkg_name="mihomo-meta"
          mihomo_meta_pkg_source_dir="${mihomo_meta_pkg_name}-${mihomo_meta_pkg_version_latest}"
          mihomo_meta_source_archive="${mihomo_meta_pkg_source_dir}.tar.gz"
          mkdir -p "${mihomo_meta_pkg_source_dir}"
          git -C mihomo-meta archive --format=tar HEAD | tar -x -f - -C "${mihomo_meta_pkg_source_dir}"
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name --mtime="@${mihomo_meta_commit_timestamp}" -c "${mihomo_meta_pkg_source_dir}" | gzip -n -c > "${mihomo_meta_source_archive}"

          echo "mihomo_meta_pkg_version_latest=${mihomo_meta_pkg_version_latest}" >> $GITHUB_OUTPUT
          echo "mihomo_meta_pkg_source_version_latest=${mihomo_meta_pkg_source_version_latest}" >> $GITHUB_OUTPUT
          echo "mihomo_meta_pkg_mirror_hash_latest=$(sha256sum ${mihomo_meta_source_archive} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
          echo "mihomo_meta_pkg_build_version_latest=${mihomo_meta_latest_tag}" >> $GITHUB_OUTPUT

  update_meta:
    needs:
      - current_mihomo
      - latest_mihomo_meta
    if: ${{ needs.current_mihomo.outputs.mihomo_meta_pkg_source_version != needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_source_version_latest }}
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: apoiston/nikki
          ref: main
          path: OpenWrt-nikki

      - name: Update mihomo meta
        run: |
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_version_latest }}/" OpenWrt-nikki/mihomo-meta/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_source_version_latest }}/" OpenWrt-nikki/mihomo-meta/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_mirror_hash_latest }}/" OpenWrt-nikki/mihomo-meta/Makefile
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_build_version_latest }}/" OpenWrt-nikki/mihomo-meta/Makefile

      - id: pr
        name: pr
        uses: peter-evans/create-pull-request@v8
        with:
          path: OpenWrt-nikki
          branch: dependabot/mihomo-meta
          commit-message: "chore: update mihomo-meta to ${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_source_version_latest }}"
          title: "chore: update mihomo-meta to ${{ needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_source_version_latest }}"
          body: |
            [Changelog](https://github.com/metacubex/mihomo/compare/${{ needs.current_mihomo.outputs.mihomo_meta_pkg_source_version }}...${{  needs.latest_mihomo_meta.outputs.mihomo_meta_pkg_source_version_latest }})
